version: '3.8'
services:
#  mysql:
#    image: mysql:8.0.32
#    container_name: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=argentina
#      - MYSQL_DATABASE=profile_app
#      - MYSQL_USER=argentina
#      - MYSQL_PASSWORD=programa
#    volumes:
#      - ./:/tmp
  spring:
    image: jdk11
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=portfolio-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - CLASSPATH=/
    volumes:
      - ./:/tmp
